// ***** start - imports from packages *****
import Head from "next/head";
import { useSelector } from "react-redux";
// ***** end - imports from packages *****

// ***** start - imports from files *****
import { wrapper } from "../hooks/useStore";
import productData from "../product.json";
import AppLayout from "@/components/Layout/AppLayout";
import MainSection from "@/components/MainSection";
// ***** end - imports from files *****

const Home = ({ product }) => {

  // ***** start - define variables *****
  const cartData = useSelector((state) => state.cart);
  // ***** end - define variables *****

  return (
    <>
      <Head>
        <title>{product.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../public/favicon.ico" />
      </Head>
      <AppLayout cartData={cartData}>
        <MainSection product={product} />
      </AppLayout>
    </>
  );
};

// ***** start - fetch product data using server side props *****
export const getServerSideProps = wrapper.getServerSideProps(() => {
  return async () => {
    const product = await productData;
    return {
      props: { product },
    };
  };
});
// ***** end - fetch product data using server side props *****

export default Home;